# Generated by Django 4.2.6 on 2023-10-08 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitznachbar',
            fields=[
                ('pers_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
                ('rec_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sitznachbar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rec_time'],
            },
        ),
    ]
