# Generated by Django 4.2.6 on 2023-10-08 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitznachbar',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitznachbar',
            name='pers_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
