# Generated by Django 4.2.6 on 2023-10-08 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolapi', '0002_sitznachbar_id_alter_sitznachbar_pers_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitznachbar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sitznachbar_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
