# Generated by Django 4.2.6 on 2023-10-08 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolapi', '0003_alter_sitznachbar_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitznachbar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sitznachbar', to=settings.AUTH_USER_MODEL),
        ),
    ]
