# Generated by Django 4.2.6 on 2023-10-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0004_alter_sitznachbar_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_desc', models.CharField(max_length=100)),
                ('sitznachbar', models.ManyToManyField(to='schoolapi.sitznachbar')),
            ],
        ),
    ]
